service: game-lambda

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/game-table"

functions:
  gameHandler:
    handler: lambdas/game/gameHandler.handler
    url: true
    environment:
      TABLE_NAME: game-table

package:
  exclude:
    - node_modules/**
    - .git/**
    - .serverless/**
    - .gitignore
    - README.md

resources:
  Resources:
    GameTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: game-table
        AttributeDefinitions:
          - AttributeName: gameId
            AttributeType: S
        KeySchema:
          - AttributeName: gameId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
